### ISSUE TITLE
Can i get a trial

### ISSUE THREAD

**Issue by dumiduLakshan** [sachinsenal0x64/the-censorship#6]
### Describe your question

I need trial vpn for testing purpose

### Enter your email if you need a 1-hour VPN trial.

dumilakshan4878@gmail.com

**Comment by sachinsenal0x64** [comment]
sure

**Comment by cryptowizes** [comment]
Enter your email if you need a 1-hour VPN trial.
vishwadilum91@gmail.com

**Comment by sachinsenal0x64** [comment]
> i need a 1-hour VPN trial. [vishwadilum91@gmail.com](mailto:vishwadilum91@gmail.com)

Done 

![image](https://github.com/sachinsenal0x64/the-censorship/assets/127573781/ae6e07eb-3123-4adc-8e9e-2eca4ef1d00f)

**Comment by sachinsenal0x64** [comment]
> dumilakshan4878@gmail.com

Done 

![image](https://github.com/sachinsenal0x64/the-censorship/assets/127573781/5072f503-0def-4b97-be45-cfd74c01b838)

**Comment by sachinsenal0x64** [comment]
For PC https://github.com/MatsuriDayo/nekoray

For Android https://github.com/MatsuriDayo/NekoBoxForAndroid

**Comment by sachinsenal0x64** [comment]
if you have any question feel free to ask cheers 🍺

**Comment by Kingnamal404** [comment]
can i get a trial

**Comment by sachinsenal0x64** [comment]
> can i get a trial

Sure send your mail
